name: Deploy Kotlin Jetpack Compose App to Amazon AppStore

on:
  push:
    branches: 
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Paso 1: Clonar el repositorio
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # Paso 2: Configurar Java
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '23.0.1'
        distribution: 'temurin'
    
    # Paso 3: Configurar Kotlin
    - name: Set up Kotlin
      uses: fwilhe2/setup-kotlin@v1
      with:
        kotlin-version: 1.9.0  
    
    # Paso 4: Configurar Gradle
    - name: Set up Gradle
      uses: gradle/gradle-build-action@v3
    
    # Paso 5: Permitir ejecución de gradlew
    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew
    
    # Paso 6: Construir la APK
    - name: Build with Gradle
      run: ./gradlew assembleProdRelease
    
    # Paso 7: Firmar la APK
    - name: Sign Android Release APK
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/apk/prod/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY_BASE64 }}
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
        alias: ${{ secrets.ALIAS }}
    
    # Paso 8: Validar la APK generada
    - name: Validate Generated APK
      run: |
        ls -l app/build/outputs/apk/prod/release/
        file app/build/outputs/apk/prod/release/*.apk
    
    # Paso 9: Subir la APK como artefacto a GitHub
    - name: Upload APK to GitHub Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: app/build/outputs/apk/prod/release/*.apk
        retention-days: 5
    
    # Paso 10: Configurar y autenticar Amazon AppStore CLI
    - name: Install Amazon AppStore CLI
      run: |
        curl -O https://appstore-sdk.amazon.com/releases/amazon-appstore-cli.zip
        unzip amazon-appstore-cli.zip -d amazon-appstore-cli
        sudo mv amazon-appstore-cli /usr/local/bin/amazon-appstore-cli
        amazon-appstore-cli --version
    
    - name: Authenticate with Amazon AppStore
      run: |
        amazon-appstore-cli auth:login \
          --email "${{ secrets.AMAZON_DEVELOPER_EMAIL }}" \
          --password "${{ secrets.AMAZON_DEVELOPER_PASSWORD }}" \
          --client-id "${{ secrets.AMAZON_CLIENT_ID }}" \
          --client-secret "${{ secrets.AMAZON_CLIENT_SECRET }}"
    
    # Paso 11: Subir la APK a Amazon AppStore
    - name: Upload APK to Amazon AppStore
      run: |
        amazon-appstore-cli submissions:create \
          --package-name "com.example.ligasmartapp" \
          --apk "app/build/outputs/apk/prod/release/ligasmartapp.apk" \
          --title "LigaSmart App" \
          --description "Gestión de ligas y torneos de fútbol local"
    
    # Paso 12: Confirmar envío
    - name: Confirm Submission
      run: echo "¡La aplicación ha sido enviada correctamente a Amazon AppStore!"
